spring.application.name=practice01
# ?? ??
server.port=8090

# Thymeleaf ??
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML


# DevTools ?? ???
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
